@URL = http://localhost:4000

#### Post List ####
POST {{URL}}
Content-Type: application/json
Authorization: Bearer xxx
X-REQUEST-TYPE: GraphQL

query Posts {
  posts {
    id,
    body,
    userId,
    title
  }
}

#### View ####

POST {{URL}}
Content-Type: application/json
Authorization: Bearer xxx
X-REQUEST-TYPE: GraphQL

query Post($postId: Int!) {
  post(id: $postId) {
    id,
    body,
    userId,
    title
  }
}

{
  "postId" : 1
}

#### Create ####
POST {{URL}}
Content-Type: application/json
Authorization: Bearer xxx
X-REQUEST-TYPE: GraphQL

mutation createPost($userId: Int!, $title: String!, $body: String!) {
  createPost(userId: $userId, title: $title, body: $body) {
    userId
    id
    title
    body
  }
}

{
  "userId": 1,
  "title": "title",
  "body": "body"
}

#### Update ####
POST {{URL}}
Content-Type: application/json
Authorization: Bearer xxx
X-REQUEST-TYPE: GraphQL

mutation UpdatePost($updatePostId: Int!, $userId: Int!, $title: String!, $body: String!) {
  updatePost(id: $updatePostId, userId: $userId, title: $title, body: $body) {
    userId
    id
    title
    body
    lastName
  }
}

{
  "updatePostId": 1,
  "userId": 1,
  "title": "Title 1",
  "body": "Body 1"
}

#### Delete ####
POST {{URL}}
Content-Type: application/json
Authorization: Bearer xxx
X-REQUEST-TYPE: GraphQL

mutation deletePost($postId: Int!) {
  deletePost(id: $postId)
}

{
  "postId": 11
}